language: python
cache: pip
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - echo "Hello"
  - ls
  - if [ "${TRAVIS_BRANCH}" == "test-branch" ]; then echo "It is working" ; fi
  - echo "fiished"
