language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
before_script:
  - mv chromedriver /usr/bin
  - chmod a+x chromedriver
  - python -m SimpleHTTPServer &
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - python get_screenshot.py