language: python
cache: pip
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - echo "Hello"
  - ls
  - ./build-travis.sh
  - echo "fiished"
  - echo "working"

branches:
  except:
    - master
    
branches:
  only:
    - test-branch
